import '../models/city.dart';

final List<City> allIndianCities = [
  City(name: 'Mumbai', state: 'Maharashtra'),
  City(name: 'Delhi', state: 'Delhi'),
  City(name: 'Bengaluru', state: 'Karnataka'),
  City(name: 'Ahmedabad', state: 'Gujarat'),
  City(name: 'Hyderabad', state: 'Telangana'),
  City(name: 'Chennai', state: 'Tamil Nadu'),
  City(name: 'Kolkata', state: 'West Bengal'),
  City(name: 'Pune', state: 'Maharashtra'),
  City(name: 'Jaipur', state: 'Rajasthan'),
  City(name: 'Surat', state: 'Gujarat'),
  City(name: 'Lucknow', state: 'Uttar Pradesh'),
  City(name: 'Kanpur', state: 'Uttar Pradesh'),
  City(name: 'Nagpur', state: 'Maharashtra'),
  City(name: 'Patna', state: 'Bihar'),
  City(name: 'Indore', state: 'Madhya Pradesh'),
  City(name: 'Thane', state: 'Maharashtra'),
  City(name: 'Bhopal', state: 'Madhya Pradesh'),
  City(name: 'Visakhapatnam', state: 'Andhra Pradesh'),
  City(name: 'Vadodara', state: 'Gujarat'),
  City(name: 'Firozabad', state: 'Uttar Pradesh'),
  City(name: 'Ludhiana', state: 'Punjab'),
  City(name: 'Rajkot', state: 'Gujarat'),
  City(name: 'Agra', state: 'Uttar Pradesh'),
  City(name: 'Siliguri', state: 'West Bengal'),
  City(name: 'Nashik', state: 'Maharashtra'),
  City(name: 'Faridabad', state: 'Haryana'),
  City(name: 'Patiala', state: 'Punjab'),
  City(name: 'Meerut', state: 'Uttar Pradesh'),
  City(name: 'Kalyan-Dombivali', state: 'Maharashtra'),
  City(name: 'Vasai-Virar', state: 'Maharashtra'),
  City(name: 'Varanasi', state: 'Uttar Pradesh'),
  City(name: 'Srinagar', state: 'Jammu and Kashmir'),
  City(name: 'Dhanbad', state: 'Jharkhand'),
  City(name: 'Jodhpur', state: 'Rajasthan'),
  City(name: 'Amritsar', state: 'Punjab'),
  City(name: 'Raipur', state: 'Chhattisgarh'),
  City(name: 'Allahabad', state: 'Uttar Pradesh'),
  City(name: 'Coimbatore', state: 'Tamil Nadu'),
  City(name: 'Jabalpur', state: 'Madhya Pradesh'),
  City(name: 'Gwalior', state: 'Madhya Pradesh'),
  City(name: 'Vijayawada', state: 'Andhra Pradesh'),
  City(name: 'Madurai', state: 'Tamil Nadu'),
  City(name: 'Guwahati', state: 'Assam'),
  City(name: 'Chandigarh', state: 'Chandigarh'),
  City(name: 'Hubli-Dharwad', state: 'Karnataka'),
  City(name: 'Amroha', state: 'Uttar Pradesh'),
  City(name: 'Moradabad', state: 'Uttar Pradesh'),
  City(name: 'Gurgaon', state: 'Haryana'),
  City(name: 'Aligarh', state: 'Uttar Pradesh'),
  City(name: 'Solapur', state: 'Maharashtra'),
  City(name: 'Ranchi', state: 'Jharkhand'),
  City(name: 'Jalandhar', state: 'Punjab'),
  City(name: 'Tiruchirappalli', state: 'Tamil Nadu'),
  City(name: 'Bhubaneswar', state: 'Odisha'),
  City(name: 'Salem', state: 'Tamil Nadu'),
  City(name: 'Warangal', state: 'Telangana'),
  City(name: 'Mira-Bhayandar', state: 'Maharashtra'),
  City(name: 'Thiruvananthapuram', state: 'Kerala'),
  City(name: 'Bhiwandi', state: 'Maharashtra'),
  City(name: 'Saharanpur', state: 'Uttar Pradesh'),
  City(name: 'Guntur', state: 'Andhra Pradesh'),
  City(name: 'Amravati', state: 'Maharashtra'),
  City(name: 'Bikaner', state: 'Rajasthan'),
  City(name: 'Noida', state: 'Uttar Pradesh'),
  City(name: 'Jamshedpur', state: 'Jharkhand'),
  City(name: 'Bhilai Nagar', state: 'Chhattisgarh'),
  City(name: 'Cuttack', state: 'Odisha'),
  City(name: 'Kochi', state: 'Kerala'),
  City(name: 'Udaipur', state: 'Rajasthan'),
  City(name: 'Bhavnagar', state: 'Gujarat'),
  City(name: 'Dehradun', state: 'Uttarakhand'),
  City(name: 'Asansol', state: 'West Bengal'),
  City(name: 'Nanded-Waghala', state: 'Maharashtra'),
  City(name: 'Ajmer', state: 'Rajasthan'),
  City(name: 'Jamnagar', state: 'Gujarat'),
  City(name: 'Ujjain', state: 'Madhya Pradesh'),
  City(name: 'Sangli', state: 'Maharashtra'),
  City(name: 'Loni', state: 'Uttar Pradesh'),
  City(name: 'Jhansi', state: 'Uttar Pradesh'),
  City(name: 'Pondicherry', state: 'Puducherry'),
  City(name: 'Nellore', state: 'Andhra Pradesh'),
  City(name: 'Jammu', state: 'Jammu and Kashmir'),
  City(name: 'Belagavi', state: 'Karnataka'),
  City(name: 'Raurkela', state: 'Odisha'),
  City(name: 'Mangaluru', state: 'Karnataka'),
  City(name: 'Tirunelveli', state: 'Tamil Nadu'),
  City(name: 'Malegaon', state: 'Maharashtra'),
  City(name: 'Gaya', state: 'Bihar'),
  City(name: 'Tiruppur', state: 'Tamil Nadu'),
  City(name: 'Davanagere', state: 'Karnataka'),
  City(name: 'Kozhikode', state: 'Kerala'),
  City(name: 'Akola', state: 'Maharashtra'),
  City(name: 'Kurnool', state: 'Andhra Pradesh'),
  City(name: 'Bokaro Steel City', state: 'Jharkhand'),
  City(name: 'Rajahmundry', state: 'Andhra Pradesh'),
  City(name: 'Ballari', state: 'Karnataka'),
  City(name: 'Agartala', state: 'Tripura'),
  City(name: 'Bhagalpur', state: 'Bihar'),
  City(name: 'Latur', state: 'Maharashtra'),
  City(name: 'Dhule', state: 'Maharashtra'),
  City(name: 'Korba', state: 'Chhattisgarh'),
  City(name: 'Bhilwara', state: 'Rajasthan'),
  City(name: 'Brahmapur', state: 'Odisha'),
  City(name: 'Mysore', state: 'Karnataka'),
  City(name: 'Muzaffarpur', state: 'Bihar'),
  City(name: 'Ahmednagar', state: 'Maharashtra'),
  City(name: 'Kollam', state: 'Kerala'),
  City(name: 'Raghunathganj', state: 'West Bengal'),
  City(name: 'Bilaspur', state: 'Chhattisgarh'),
  City(name: 'Shahjahanpur', state: 'Uttar Pradesh'),
  City(name: 'Thrissur', state: 'Kerala'),
  City(name: 'Alwar', state: 'Rajasthan'),
  City(name: 'Kakinada', state: 'Andhra Pradesh'),
  City(name: 'Nizamabad', state: 'Telangana'),
  City(name: 'Sagar', state: 'Madhya Pradesh'),
  City(name: 'Tumkur', state: 'Karnataka'),
  City(name: 'Hisar', state: 'Haryana'),
  City(name: 'Rohtak', state: 'Haryana'),
  City(name: 'Panipat', state: 'Haryana'),
  City(name: 'Darbhanga', state: 'Bihar'),
  City(name: 'Kharagpur', state: 'West Bengal'),
  City(name: 'Aizawl', state: 'Mizoram'),
  City(name: 'Ichalkaranji', state: 'Maharashtra'),
  City(name: 'Tirupati', state: 'Andhra Pradesh'),
  City(name: 'Karnal', state: 'Haryana'),
  City(name: 'Bathinda', state: 'Punjab'),
  City(name: 'Rampur', state: 'Uttar Pradesh'),
  City(name: 'Shivamogga', state: 'Karnataka'),
  City(name: 'Ratlam', state: 'Madhya Pradesh'),
  City(name: 'Modinagar', state: 'Uttar Pradesh'),
  City(name: 'Durg', state: 'Chhattisgarh'),
  City(name: 'Shillong', state: 'Meghalaya'),
  City(name: 'Imphal', state: 'Manipur'),
  City(name: 'Hapur', state: 'Uttar Pradesh'),
  City(name: 'Ranipet', state: 'Tamil Nadu'),
  City(name: 'Anantapur', state: 'Andhra Pradesh'),
  City(name: 'Arrah', state: 'Bihar'),
  City(name: 'Karimnagar', state: 'Telangana'),
  City(name: 'Parbhani', state: 'Maharashtra'),
  City(name: 'Etawah', state: 'Uttar Pradesh'),
  City(name: 'Bharatpur', state: 'Rajasthan'),
  City(name: 'Begusarai', state: 'Bihar'),
  City(name: 'New Delhi', state: 'Delhi'),
  City(name: 'Chhapra', state: 'Bihar'),
  City(name: 'Kadapa', state: 'Andhra Pradesh'),
  City(name: 'Ramagundam', state: 'Telangana'),
  City(name: 'Pali', state: 'Rajasthan'),
  City(name: 'Satna', state: 'Madhya Pradesh'),
  City(name: 'Vizianagaram', state: 'Andhra Pradesh'),
  City(name: 'Katihar', state: 'Bihar'),
  City(name: 'Hardwar', state: 'Uttarakhand'),
  City(name: 'Sonipat', state: 'Haryana'),
  City(name: 'Nagercoil', state: 'Tamil Nadu'),
  City(name: 'Thanjavur', state: 'Tamil Nadu'),
  City(name: 'Murwara (Katni)', state: 'Madhya Pradesh'),
  City(name: 'Naihati', state: 'West Bengal'),
  City(name: 'Sambhal', state: 'Uttar Pradesh'),
  City(name: 'Nadiad', state: 'Gujarat'),
  City(name: 'Yamunanagar', state: 'Haryana'),
  City(name: 'English Bazar', state: 'West Bengal'),
  City(name: 'Eluru', state: 'Andhra Pradesh'),
  City(name: 'Munger', state: 'Bihar'),
  City(name: 'Panchkula', state: 'Haryana'),
  City(name: 'Raayachuru', state: 'Karnataka'),
  City(name: 'Panvel', state: 'Maharashtra'),
  City(name: 'Deoghar', state: 'Jharkhand'),
  City(name: 'Ongole', state: 'Andhra Pradesh'),
  City(name: 'Nandyal', state: 'Andhra Pradesh'),
  City(name: 'Morena', state: 'Madhya Pradesh'),
  City(name: 'Bhiwani', state: 'Haryana'),
  City(name: 'Porbandar', state: 'Gujarat'),
  City(name: 'Palakkad', state: 'Kerala'),
  City(name: 'Anand', state: 'Gujarat'),
  City(name: 'Purnia', state: 'Bihar'),
  City(name: 'Baharampur', state: 'West Bengal'),
  City(name: 'Barmer', state: 'Rajasthan'),
  City(name: 'Morvi', state: 'Gujarat'),
  City(name: 'Orai', state: 'Uttar Pradesh'),
  City(name: 'Bahraich', state: 'Uttar Pradesh'),
  City(name: 'Sikar', state: 'Rajasthan'),
  City(name: 'Vellore', state: 'Tamil Nadu'),
  City(name: 'Singrauli', state: 'Madhya Pradesh'),
  City(name: 'Khammam', state: 'Telangana'),
  City(name: 'Mahesana', state: 'Gujarat'),
  City(name: 'Silchar', state: 'Assam'),
  City(name: 'Sambalpur', state: 'Odisha'),
  City(name: 'Rewa', state: 'Madhya Pradesh'),
  City(name: 'Unnao', state: 'Uttar Pradesh'),
  City(name: 'Hugli-Chinsurah', state: 'West Bengal'),
  City(name: 'Raiganj', state: 'West Bengal'),
  City(name: 'Phusro', state: 'Jharkhand'),
  City(name: 'Adityapur', state: 'Jharkhand'),
  City(name: 'Alappuzha', state: 'Kerala'),
  City(name: 'Bahadurgarh', state: 'Haryana'),
  City(name: 'Machilipatnam', state: 'Andhra Pradesh'),
  City(name: 'Rae Bareli', state: 'Uttar Pradesh'),
  City(name: 'Jalpaiguri', state: 'West Bengal'),
  City(name: 'Bharuch', state: 'Gujarat'),
  City(name: 'Pathankot', state: 'Punjab'),
  City(name: 'Hoshiarpur', state: 'Punjab'),
  City(name: 'Baramula', state: 'Jammu and Kashmir'),
  City(name: 'Adoni', state: 'Andhra Pradesh'),
  City(name: 'Jind', state: 'Haryana'),
  City(name: 'Tonk', state: 'Rajasthan'),
  City(name: 'Tenali', state: 'Andhra Pradesh'),
  City(name: 'Kancheepuram', state: 'Tamil Nadu'),
  City(name: 'Vapi', state: 'Gujarat'),
  City(name: 'Sirsa', state: 'Haryana'),
  City(name: 'Navsari', state: 'Gujarat'),
  City(name: 'Mahbubnagar', state: 'Telangana'),
  City(name: 'Puri', state: 'Odisha'),
  City(name: 'Robertson Pet', state: 'Karnataka'),
  City(name: 'Erode', state: 'Tamil Nadu'),
  City(name: 'Batala', state: 'Punjab'),
  City(name: 'Haldwani-cum-Kathgodam', state: 'Uttarakhand'),
  City(name: 'Vidisha', state: 'Madhya Pradesh'),
  City(name: 'Saharsa', state: 'Bihar'),
  City(name: 'Thanesar', state: 'Haryana'),
  City(name: 'Chittoor', state: 'Andhra Pradesh'),
  City(name: 'Veraval', state: 'Gujarat'),
  City(name: 'Lakhimpur', state: 'Uttar Pradesh'),
  City(name: 'Sitapur', state: 'Uttar Pradesh'),
  City(name: 'Hindupur', state: 'Andhra Pradesh'),
  City(name: 'Santipur', state: 'West Bengal'),
  City(name: 'Balurghat', state: 'West Bengal'),
  City(name: 'Ganjbasoda', state: 'Madhya Pradesh'),
  City(name: 'Moga', state: 'Punjab'),
  City(name: 'Proddatur', state: 'Andhra Pradesh'),
  City(name: 'Srinagar', state: 'Uttarakhand'),
  City(name: 'Medinipur', state: 'West Bengal'),
  City(name: 'Habra', state: 'West Bengal'),
  City(name: 'Sasaram', state: 'Bihar'),
  City(name: 'Hajipur', state: 'Bihar'),
  City(name: 'Bhuj', state: 'Gujarat'),
  City(name: 'Shivpuri', state: 'Madhya Pradesh'),
  City(name: 'Ranaghat', state: 'West Bengal'),
  City(name: 'Shimla', state: 'Himachal Pradesh'),
  City(name: 'Tiruvannamalai', state: 'Tamil Nadu'),
  City(name: 'Kaithal', state: 'Haryana'),
  City(name: 'Rajnandgaon', state: 'Chhattisgarh'),
  City(name: 'Godhra', state: 'Gujarat'),
  City(name: 'Hazaribag', state: 'Jharkhand'),
  City(name: 'Bhimavaram', state: 'Andhra Pradesh'),
  City(name: 'Mandsaur', state: 'Madhya Pradesh'),
  City(name: 'Dibrugarh', state: 'Assam'),
  City(name: 'Kolar', state: 'Karnataka'),
  City(name: 'Bankura', state: 'West Bengal'),
  City(name: 'Mandya', state: 'Karnataka'),
  City(name: 'Dehri-on-Sone', state: 'Bihar'),
  City(name: 'Madanapalle', state: 'Andhra Pradesh'),
  City(name: 'Malerkotla', state: 'Punjab'),
  City(name: 'Lalitpur', state: 'Uttar Pradesh'),
  City(name: 'Bettiah', state: 'Bihar'),
  City(name: 'Pollachi', state: 'Tamil Nadu'),
  City(name: 'Khanna', state: 'Punjab'),
  City(name: 'Neemuch', state: 'Madhya Pradesh'),
  City(name: 'Palwal', state: 'Haryana'),
  City(name: 'Palanpur', state: 'Gujarat'),
  City(name: 'Guntakal', state: 'Andhra Pradesh'),
  City(name: 'Nabadwip', state: 'West Bengal'),
  City(name: 'Udupi', state: 'Karnataka'),
  City(name: 'Jagdalpur', state: 'Chhattisgarh'),
  City(name: 'Motihari', state: 'Bihar'),
  City(name: 'Pilibhit', state: 'Uttar Pradesh'),
  City(name: 'Dimapur', state: 'Nagaland'),
  City(name: 'Mohali', state: 'Punjab'),
  City(name: 'Sadulpur', state: 'Rajasthan'),
  City(name: 'Rajapalayam', state: 'Tamil Nadu'),
  City(name: 'Dharmavaram', state: 'Andhra Pradesh'),
  City(name: 'Kashipur', state: 'Uttarakhand'),
  City(name: 'Sivakasi', state: 'Tamil Nadu'),
  City(name: 'Darjiling', state: 'West Bengal'),
  City(name: 'Chikkamagaluru', state: 'Karnataka'),
  City(name: 'Gudivada', state: 'Andhra Pradesh'),
  City(name: 'Baleshwar Town', state: 'Odisha'),
  City(name: 'Mancherial', state: 'Telangana'),
  City(name: 'Srikakulam', state: 'Andhra Pradesh'),
  City(name: 'Adilabad', state: 'Telangana'),
  City(name: 'Yavatmal', state: 'Maharashtra'),
  City(name: 'Barnala', state: 'Punjab'),
  City(name: 'Nagaon', state: 'Assam'),
  City(name: 'Narasaraopet', state: 'Andhra Pradesh'),
  City(name: 'Raigarh', state: 'Chhattisgarh'),
  City(name: 'Roorkee', state: 'Uttarakhand'),
  City(name: 'Valsad', state: 'Gujarat'),
  City(name: 'Ambikapur', state: 'Chhattisgarh'),
  City(name: 'Giridih', state: 'Jharkhand'),
  City(name: 'Chandausi', state: 'Uttar Pradesh'),
  City(name: 'Purulia', state: 'West Bengal'),
  City(name: 'Patan', state: 'Gujarat'),
  City(name: 'Bagaha', state: 'Bihar'),
  City(name: 'Hardoi ', state: 'Uttar Pradesh'),
  City(name: 'Achalpur', state: 'Maharashtra'),
  City(name: 'Osmanabad', state: 'Maharashtra'),
  City(name: 'Deesa', state: 'Gujarat'),
  City(name: 'Nandurbar', state: 'Maharashtra'),
  City(name: 'Azamgarh', state: 'Uttar Pradesh'),
  City(name: 'Ramgarh', state: 'Jharkhand'),
  City(name: 'Firozpur', state: 'Punjab'),
  City(name: 'Baripada Town', state: 'Odisha'),
  City(name: 'Karwar', state: 'Karnataka'),
  City(name: 'Siwan', state: 'Bihar'),
  City(name: 'Rajampet', state: 'Andhra Pradesh'),
  City(name: 'Pudukkottai', state: 'Tamil Nadu'),
  City(name: 'Anantnag', state: 'Jammu and Kashmir'),
  City(name: 'Tadpatri', state: 'Andhra Pradesh'),
  City(name: 'Satara', state: 'Maharashtra'),
  City(name: 'Bhadrak', state: 'Odisha'),
  City(name: 'Kishanganj', state: 'Bihar'),
  City(name: 'Suryapet', state: 'Telangana'),
  City(name: 'Wardha', state: 'Maharashtra'),
  City(name: 'Ranebennuru', state: 'Karnataka'),
  City(name: 'Amreli', state: 'Gujarat'),
  City(name: 'Neyveli (TS)', state: 'Tamil Nadu'),
  City(name: 'Jamalpur', state: 'Bihar'),
  City(name: 'Marmagao', state: 'Goa'),
  City(name: 'Udgir', state: 'Maharashtra'),
  City(name: 'Tadepalligudem', state: 'Andhra Pradesh'),
  City(name: 'Nagapattinam', state: 'Tamil Nadu'),
  City(name: 'Buxar', state: 'Bihar'),
  City(name: 'Aurangabad', state: 'Maharashtra'),
  City(name: 'Jehanabad', state: 'Bihar'),
  City(name: 'Phagwara', state: 'Punjab'),
  City(name: 'Khair', state: 'Uttar Pradesh'),
  City(name: 'Sawai Madhopur', state: 'Rajasthan'),
  City(name: 'Kapurthala', state: 'Punjab'),
  City(name: 'Chilakaluripet', state: 'Andhra Pradesh'),
  City(name: 'Aurangabad', state: 'Bihar'),
  City(name: 'Malappuram', state: 'Kerala'),
  City(name: 'Rewari', state: 'Haryana'),
  City(name: 'Nagaur', state: 'Rajasthan'),
  City(name: 'Sultanpur', state: 'Uttar Pradesh'),
  City(name: 'Nagda', state: 'Madhya Pradesh'),
  City(name: 'Port Blair', state: 'Andaman and Nicobar Islands'),
  City(name: 'Lakhisarai', state: 'Bihar'),
  City(name: 'Panaji', state: 'Goa'),
  City(name: 'Tinsukia', state: 'Assam'),
  City(name: 'Itarsi', state: 'Madhya Pradesh'),
  City(name: 'Kohima', state: 'Nagaland'),
  City(name: 'Balangir', state: 'Odisha'),
  City(name: 'Nawada', state: 'Bihar'),
  City(name: 'Jharsuguda', state: 'Odisha'),
  City(name: 'Jagtial', state: 'Telangana'),
  City(name: 'Viluppuram', state: 'Tamil Nadu'),
  City(name: 'Amalner', state: 'Maharashtra'),
  City(name: 'Zirakpur', state: 'Punjab'),
  City(name: 'Tanda', state: 'Uttar Pradesh'),
  City(name: 'Tiruchengode', state: 'Tamil Nadu'),
  City(name: 'Nagina', state: 'Uttar Pradesh'),
  City(name: 'Yemmiganur', state: 'Andhra Pradesh'),
  City(name: 'Vaniyambadi', state: 'Tamil Nadu'),
  City(name: 'Sarni', state: 'Madhya Pradesh'),
  City(name: 'Theni Allinagaram', state: 'Tamil Nadu'),
  City(name: 'Margao', state: 'Goa'),
  City(name: 'Akot', state: 'Maharashtra'),
  City(name: 'Sehore', state: 'Madhya Pradesh'),
  City(name: 'Mhow Cantonment', state: 'Madhya Pradesh'),
  City(name: 'Kot Kapura', state: 'Punjab'),
  City(name: 'Makrana', state: 'Rajasthan'),
  City(name: 'Pandharpur', state: 'Maharashtra'),
  City(name: 'Miryalaguda', state: 'Telangana'),
  City(name: 'Shamli', state: 'Uttar Pradesh'),
  City(name: 'Seoni', state: 'Madhya Pradesh'),
  City(name: 'Ranibennur', state: 'Karnataka'),
  City(name: 'Kadiri', state: 'Andhra Pradesh'),
  City(name: 'Shrirampur', state: 'Maharashtra'),
  City(name: 'Rudrapur', state: 'Uttarakhand'),
  City(name: 'Parli', state: 'Maharashtra'),
  City(name: 'Najibabad', state: 'Uttar Pradesh'),
  City(name: 'Nirmal', state: 'Telangana'),
  City(name: 'Udhagamandalam', state: 'Tamil Nadu'),
  City(name: 'Shikohabad', state: 'Uttar Pradesh'),
  City(name: 'Jhumri Tilaiya', state: 'Jharkhand'),
  City(name: 'Aruppukkottai', state: 'Tamil Nadu'),
  City(name: 'Ponnani', state: 'Kerala'),
  City(name: 'Jamui', state: 'Bihar'),
  City(name: 'Sitamarhi', state: 'Bihar'),
  City(name: 'Chirala', state: 'Andhra Pradesh'),
  City(name: 'Anjar', state: 'Gujarat'),
  City(name: 'Karaikal', state: 'Puducherry'),
  City(name: 'Hansi', state: 'Haryana'),
  City(name: 'Anakapalle', state: 'Andhra Pradesh'),
  City(name: 'Mahasamund', state: 'Chhattisgarh'),
  City(name: 'Faridkot', state: 'Punjab'),
  City(name: 'Saunda', state: 'Jharkhand'),
  City(name: 'Dhoraji', state: 'Gujarat'),
  City(name: 'Paramakudi', state: 'Tamil Nadu'),
  City(name: 'Balaghat', state: 'Madhya Pradesh'),
  City(name: 'Sujangarh', state: 'Rajasthan'),
  City(name: 'Khambhat', state: 'Gujarat'),
  City(name: 'Muktsar', state: 'Punjab'),
  City(name: 'Rajpura', state: 'Punjab'),
  City(name: 'Kavali', state: 'Andhra Pradesh'),
  City(name: 'Dhamtari', state: 'Chhattisgarh'),
  City(name: 'Ashok Nagar', state: 'Madhya Pradesh'),
  City(name: 'Sardarshahar', state: 'Rajasthan'),
  City(name: 'Mahuva', state: 'Gujarat'),
  City(name: 'Bargarh', state: 'Odisha'),
  City(name: 'Kamareddy', state: 'Telangana'),
  City(name: 'Sahibganj', state: 'Jharkhand'),
  City(name: 'Kothagudem', state: 'Telangana'),
  City(name: 'Ramanagaram', state: 'Karnataka'),
  City(name: 'Gokak', state: 'Karnataka'),
  City(name: 'Tikamgarh', state: 'Madhya Pradesh'),
  City(name: 'Araria', state: 'Bihar'),
  City(name: 'Rishikesh', state: 'Uttarakhand'),
  City(name: 'Shahdol', state: 'Madhya Pradesh'),
  City(name: 'Medininagar (Daltonganj)', state: 'Jharkhand'),
  City(name: 'Arakkonam', state: 'Tamil Nadu'),
  City(name: 'Washim', state: 'Maharashtra'),
  City(name: 'Sangrur', state: 'Punjab'),
  City(name: 'Bodhan', state: 'Telangana'),
  City(name: 'Fazilka', state: 'Punjab'),
  City(name: 'Palacole', state: 'Andhra Pradesh'),
  City(name: 'Keshod', state: 'Gujarat'),
  City(name: 'Sullurpeta', state: 'Andhra Pradesh'),
  City(name: 'Wadhwan', state: 'Gujarat'),
  City(name: 'Gurdaspur', state: 'Punjab'),
  City(name: 'Vatakara', state: 'Kerala'),
  City(name: 'Tura', state: 'Meghalaya'),
  City(name: 'Narnaul', state: 'Haryana'),
  City(name: 'Kharar', state: 'Punjab'),
  City(name: 'Yadgir', state: 'Karnataka'),
  City(name: 'Ambejogai', state: 'Maharashtra'),
  City(name: 'Ankleshwar', state: 'Gujarat'),
  City(name: 'Savarkundla', state: 'Gujarat'),
  City(name: 'Paradip', state: 'Odisha'),
  City(name: 'Virudhachalam', state: 'Tamil Nadu'),
  City(name: 'Kanhangad', state: 'Kerala'),
  City(name: 'Kadi', state: 'Gujarat'),
  City(name: 'Srivilliputhur', state: 'Tamil Nadu'),
  City(name: 'Gobindgarh', state: 'Punjab'),
  City(name: 'Tindivanam', state: 'Tamil Nadu'),
  City(name: 'Mansa', state: 'Punjab'),
  City(name: 'Taliparamba', state: 'Kerala'),
  City(name: 'Manmad', state: 'Maharashtra'),
  City(name: 'Tanuku', state: 'Andhra Pradesh'),
  City(name: 'Rayachoti', state: 'Andhra Pradesh'),
  City(name: 'Virudhunagar', state: 'Tamil Nadu'),
  City(name: 'Koyilandy', state: 'Kerala'),
  City(name: 'Jorhat', state: 'Assam'),
  City(name: 'Karur', state: 'Tamil Nadu'),
  City(name: 'Valparai', state: 'Tamil Nadu'),
  City(name: 'Srikalahasti', state: 'Andhra Pradesh'),
  City(name: 'Neyyattinkara', state: 'Kerala'),
  City(name: 'Bapatla', state: 'Andhra Pradesh'),
  City(name: 'Fatehabad', state: 'Haryana'),
  City(name: 'Malout', state: 'Punjab'),
  City(name: 'Sankarankovil', state: 'Tamil Nadu'),
  City(name: 'Tenkasi', state: 'Tamil Nadu'),
  City(name: 'Ratnagiri', state: 'Maharashtra'),
  City(name: 'Rabkavi Banhatti', state: 'Karnataka'),
  City(name: 'Sikandrabad', state: 'Uttar Pradesh'),
  City(name: 'Chaibasa', state: 'Jharkhand'),
  City(name: 'Chirmiri', state: 'Chhattisgarh'),
  City(name: 'Palwancha', state: 'Telangana'),
  City(name: 'Bhawanipatna', state: 'Odisha'),
  City(name: 'Kayamkulam', state: 'Kerala'),
  City(name: 'Pithampur', state: 'Madhya Pradesh'),
  City(name: 'Nabha', state: 'Punjab'),
  City(name: 'Shahabad, Hardoi', state: 'Uttar Pradesh'),
  City(name: 'Dhenkanal', state: 'Odisha'),
  City(name: 'Uran Islampur', state: 'Maharashtra'),
  City(name: 'Gopalganj', state: 'Bihar'),
  City(name: 'Bongaigaon City', state: 'Assam'),
  City(name: 'Palani', state: 'Tamil Nadu'),
  City(name: 'Pusad', state: 'Maharashtra'),
  City(name: 'Sopore', state: 'Jammu and Kashmir'),
  City(name: 'Pilkhuwa', state: 'Uttar Pradesh'),
  City(name: 'Tarn Taran', state: 'Punjab'),
  City(name: 'Renukoot', state: 'Uttar Pradesh'),
  City(name: 'Mandamarri', state: 'Telangana'),
  City(name: 'Shahabad', state: 'Karnataka'),
  City(name: 'Barbil', state: 'Odisha'),
  City(name: 'Koratla', state: 'Telangana'),
  City(name: 'Madhubani', state: 'Bihar'),
  City(name: 'Arambagh', state: 'West Bengal'),
  City(name: 'Gohana', state: 'Haryana'),
  City(name: 'Ladnu', state: 'Rajasthan'),
  City(name: 'Pattukkottai', state: 'Tamil Nadu'),
  City(name: 'Sirsi', state: 'Karnataka'),
  City(name: 'Sircilla', state: 'Telangana'),
  City(name: 'Tamluk', state: 'West Bengal'),
  City(name: 'Jagraon', state: 'Punjab'),
  City(name: 'AlipurdUrban Agglomerationr', state: 'West Bengal'),
  City(name: 'Alirajpur', state: 'Madhya Pradesh'),
  City(name: 'Tandur', state: 'Telangana'),
  City(name: 'Naidupet', state: 'Andhra Pradesh'),
  City(name: 'Tirupathur', state: 'Tamil Nadu'),
  City(name: 'Tohana', state: 'Haryana'),
  City(name: 'Ratangarh', state: 'Rajasthan'),
  City(name: 'Dhubri', state: 'Assam'),
  City(name: 'Masaurhi', state: 'Bihar'),
  City(name: 'Visnagar', state: 'Gujarat'),
  City(name: 'Vrindavan', state: 'Uttar Pradesh'),
  City(name: 'Nokha', state: 'Rajasthan'),
  City(name: 'Nagari', state: 'Andhra Pradesh'),
  City(name: 'Narwana', state: 'Haryana'),
  City(name: 'Ramanathapuram', state: 'Tamil Nadu'),
  City(name: 'Ujhani', state: 'Uttar Pradesh'),
  City(name: 'Samastipur', state: 'Bihar'),
  City(name: 'Laharpur', state: 'Uttar Pradesh'),
  City(name: 'Sangamner', state: 'Maharashtra'),
  City(name: 'Nimbahera', state: 'Rajasthan'),
  City(name: 'Siddipet', state: 'Telangana'),
  City(name: 'Suri', state: 'West Bengal'),
  City(name: 'Diphu', state: 'Assam'),
  City(name: 'Jhargram', state: 'West Bengal'),
  City(name: 'Shirpur-Warwade', state: 'Maharashtra'),
  City(name: 'Tilhar', state: 'Uttar Pradesh'),
  City(name: 'Sindhnur', state: 'Karnataka'),
  City(name: 'Udumalaipettai', state: 'Tamil Nadu'),
  City(name: 'Malkapur', state: 'Maharashtra'),
  City(name: 'Wanaparthy', state: 'Telangana'),
  City(name: 'Gudur', state: 'Andhra Pradesh'),
  City(name: 'Kendujhar', state: 'Odisha'),
  City(name: 'Mandla', state: 'Madhya Pradesh'),
  City(name: 'Mandi', state: 'Himachal Pradesh'),
  City(name: 'Nedumangad', state: 'Kerala'),
  City(name: 'North Lakhimpur', state: 'Assam'),
  City(name: 'Vinukonda', state: 'Andhra Pradesh'),
  City(name: 'Tiptur', state: 'Karnataka'),
  City(name: 'Gobichettipalayam', state: 'Tamil Nadu'),
  City(name: 'Sunabeda', state: 'Odisha'),
  City(name: 'Wani', state: 'Maharashtra'),
  City(name: 'Upleta', state: 'Gujarat'),
  City(name: 'Narasapuram', state: 'Andhra Pradesh'),
  City(name: 'Nuzvid', state: 'Andhra Pradesh'),
  City(name: 'Tezpur', state: 'Assam'),
  City(name: 'Una', state: 'Gujarat'),
  City(name: 'Markapur', state: 'Andhra Pradesh'),
  City(name: 'Sheopur', state: 'Madhya Pradesh'),
  City(name: 'Thiruvarur', state: 'Tamil Nadu'),
  City(name: 'Sidhpur', state: 'Gujarat'),
  City(name: 'Sahaswan', state: 'Uttar Pradesh'),
  City(name: 'Suratgarh', state: 'Rajasthan'),
  City(name: 'Shajapur', state: 'Madhya Pradesh'),
  City(name: 'Rayagada', state: 'Odisha'),
  City(name: 'Lonavla', state: 'Maharashtra'),
  City(name: 'Ponnur', state: 'Andhra Pradesh'),
  City(name: 'Kagaznagar', state: 'Telangana'),
  City(name: 'Gadwal', state: 'Telangana'),
  City(name: 'Bhatapara', state: 'Chhattisgarh'),
  City(name: 'Kandukur', state: 'Andhra Pradesh'),
  City(name: 'Sangareddy', state: 'Telangana'),
  City(name: 'Unjha', state: 'Gujarat'),
  City(name: 'Lunglei', state: 'Mizoram'),
  City(name: 'Karimganj', state: 'Assam'),
  City(name: 'Kannur', state: 'Kerala'),
  City(name: 'Bobbili', state: 'Andhra Pradesh'),
  City(name: 'Mokameh', state: 'Bihar'),
  City(name: 'Talegaon Dabhade', state: 'Maharashtra'),
  City(name: 'Anjangaon', state: 'Maharashtra'),
  City(name: 'Mangrol', state: 'Gujarat'),
  City(name: 'Sunam', state: 'Punjab'),
  City(name: 'Gangarampur', state: 'West Bengal'),
  City(name: 'Thiruvallur', state: 'Tamil Nadu'),
  City(name: 'Tirur', state: 'Kerala'),
  City(name: 'Rath', state: 'Uttar Pradesh'),
  City(name: 'Jatani', state: 'Odisha'),
  City(name: 'Viramgam', state: 'Gujarat'),
  City(name: 'Rajsamand', state: 'Rajasthan'),
  City(name: 'Yanam', state: 'Puducherry'),
  City(name: 'Kottayam', state: 'Kerala'),
  City(name: 'Panruti', state: 'Tamil Nadu'),
  City(name: 'Dhuri', state: 'Punjab'),
  City(name: 'Namakkal', state: 'Tamil Nadu'),
  City(name: 'Kasaragod', state: 'Kerala'),
  City(name: 'Modasa', state: 'Gujarat'),
  City(name: 'Rayadurg', state: 'Andhra Pradesh'),
  City(name: 'Supaul', state: 'Bihar'),
  City(name: 'Kunnamkulam', state: 'Kerala'),
  City(name: 'Umred', state: 'Maharashtra'),
  City(name: 'Bellampalle', state: 'Telangana'),
  City(name: 'Sibsagar', state: 'Assam'),
  City(name: 'Mandi Dabwali', state: 'Haryana'),
  City(name: 'Ottappalam', state: 'Kerala'),
  City(name: 'Dumraon', state: 'Bihar'),
  City(name: 'Samalkot', state: 'Andhra Pradesh'),
  City(name: 'Jaggaiahpet', state: 'Andhra Pradesh'),
  City(name: 'Goalpara', state: 'Assam'),
  City(name: 'Tuni', state: 'Andhra Pradesh'),
  City(name: 'Lachhmangarh', state: 'Rajasthan'),
  City(name: 'Bhongir', state: 'Telangana'),
  City(name: 'Amalapuram', state: 'Andhra Pradesh'),
  City(name: 'Firozpur Cantt.', state: 'Punjab'),
  City(name: 'Vikarabad', state: 'Telangana'),
  City(name: 'Thiruvalla', state: 'Kerala'),
  City(name: 'Sherkot', state: 'Uttar Pradesh'),
  City(name: 'Palghar', state: 'Maharashtra'),
  City(name: 'Shegaon', state: 'Maharashtra'),
  City(name: 'Jangaon', state: 'Telangana'),
  City(name: 'Bheemunipatnam', state: 'Andhra Pradesh'),
  City(name: 'Panna', state: 'Madhya Pradesh'),
  City(name: 'Thodupuzha', state: 'Kerala'),
  City(name: 'KathUrban Agglomeration', state: 'Jammu and Kashmir'),
  City(name: 'Palitana', state: 'Gujarat'),
  City(name: 'Arwal', state: 'Bihar'),
  City(name: 'Venkatagiri', state: 'Andhra Pradesh'),
  City(name: 'Kalpi', state: 'Uttar Pradesh'),
  City(name: 'Rajgarh (Churu)', state: 'Rajasthan'),
  City(name: 'Sattenapalle', state: 'Andhra Pradesh'),
  City(name: 'Arsikere', state: 'Karnataka'),
  City(name: 'Ozar', state: 'Maharashtra'),
  City(name: 'Thirumangalam', state: 'Tamil Nadu'),
  City(name: 'Petlad', state: 'Gujarat'),
  City(name: 'Nasirabad', state: 'Rajasthan'),
  City(name: 'Phaltan', state: 'Maharashtra'),
  City(name: 'Rampurhat', state: 'West Bengal'),
  City(name: 'Nanjangud', state: 'Karnataka'),
  City(name: 'Forbesganj', state: 'Bihar'),
  City(name: 'Tundla', state: 'Uttar Pradesh'),
  City(name: 'BhabUrban Agglomeration', state: 'Bihar'),
  City(name: 'Sagara', state: 'Karnataka'),
  City(name: 'Pithapuram', state: 'Andhra Pradesh'),
  City(name: 'Sira', state: 'Karnataka'),
  City(name: 'Bhadrachalam', state: 'Telangana'),
  City(name: 'Charkhi Dadri', state: 'Haryana'),
  City(name: 'Chatra', state: 'Jharkhand'),
  City(name: 'Palasa Kasibugga', state: 'Andhra Pradesh'),
  City(name: 'Nohar', state: 'Rajasthan'),
  City(name: 'Yevla', state: 'Maharashtra'),
  City(name: 'Sirhind Fatehgarh Sahib', state: 'Punjab'),
  City(name: 'Bhainsa', state: 'Telangana'),
  City(name: 'Parvathipuram', state: 'Andhra Pradesh'),
  City(name: 'Shahade', state: 'Maharashtra'),
  City(name: 'Chalakudy', state: 'Kerala'),
  City(name: 'Narkatiaganj', state: 'Bihar'),
  City(name: 'Kapadvanj', state: 'Gujarat'),
  City(name: 'Macherla', state: 'Andhra Pradesh'),
  City(name: 'Raghogarh-Vijaypur', state: 'Madhya Pradesh'),
  City(name: 'Rupnagar', state: 'Punjab'),
  City(name: 'Naugachhia', state: 'Bihar'),
  City(name: 'Sendhwa', state: 'Madhya Pradesh'),
  City(name: 'Byasanagar', state: 'Odisha'),
  City(name: 'Sandila', state: 'Uttar Pradesh'),
  City(name: 'Gooty', state: 'Andhra Pradesh'),
  City(name: 'Salur', state: 'Andhra Pradesh'),
  City(name: 'Nanpara', state: 'Uttar Pradesh'),
  City(name: 'Sardhana', state: 'Uttar Pradesh'),
  City(name: 'Vita', state: 'Maharashtra'),
  City(name: 'Gumia', state: 'Jharkhand'),
  City(name: 'Puttur', state: 'Karnataka'),
  City(name: 'Jalandhar Cantt.', state: 'Punjab'),
  City(name: 'Nehtaur', state: 'Uttar Pradesh'),
  City(name: 'Changanassery', state: 'Kerala'),
  City(name: 'Mandapeta', state: 'Andhra Pradesh'),
  City(name: 'Dumka', state: 'Jharkhand'),
  City(name: 'Seohara', state: 'Uttar Pradesh'),
  City(name: 'Umarkhed', state: 'Maharashtra'),
  City(name: 'Madhupur', state: 'Jharkhand'),
  City(name: 'Vikramasingapuram', state: 'Tamil Nadu'),
  City(name: 'Punalur', state: 'Kerala'),
  City(name: 'Kendrapara', state: 'Odisha'),
  City(name: 'Sihor', state: 'Gujarat'),
  City(name: 'Nellikuppam', state: 'Tamil Nadu'),
  City(name: 'Samana', state: 'Punjab'),
  City(name: 'Warora', state: 'Maharashtra'),
  City(name: 'Nilambur', state: 'Kerala'),
  City(name: 'Rasipuram', state: 'Tamil Nadu'),
  City(name: 'Ramnagar', state: 'Uttarakhand'),
  City(name: 'Jammalamadugu', state: 'Andhra Pradesh'),
  City(name: 'Nawanshahr', state: 'Punjab'),
  City(name: 'Thoubal', state: 'Manipur'),
  City(name: 'Athni', state: 'Karnataka'),
  City(name: 'Cherthala', state: 'Kerala'),
  City(name: 'Sidhi', state: 'Madhya Pradesh'),
  City(name: 'Farooqnagar', state: 'Telangana'),
  City(name: 'Peddapuram', state: 'Andhra Pradesh'),
  City(name: 'Chirkunda', state: 'Jharkhand'),
  City(name: 'Pachora', state: 'Maharashtra'),
  City(name: 'Madhepura', state: 'Bihar'),
  City(name: 'Pithoragarh', state: 'Uttarakhand'),
  City(name: 'Tumsar', state: 'Maharashtra'),
  City(name: 'Phalodi', state: 'Rajasthan'),
  City(name: 'Tiruttani', state: 'Tamil Nadu'),
  City(name: 'Rampura Phul', state: 'Punjab'),
  City(name: 'Perinthalmanna', state: 'Kerala'),
  City(name: 'Padrauna', state: 'Uttar Pradesh'),
  City(name: 'Pipariya', state: 'Madhya Pradesh'),
  City(name: 'Dalli-Rajhara', state: 'Chhattisgarh'),
  City(name: 'Punganur', state: 'Andhra Pradesh'),
  City(name: 'Mattannur', state: 'Kerala'),
  City(name: 'Mathura', state: 'Uttar Pradesh'),
  City(name: 'Thakurdwara', state: 'Uttar Pradesh'),
  City(name: 'Nandivaram-Guduvancheri', state: 'Tamil Nadu'),
  City(name: 'Mulbagal', state: 'Karnataka'),
  City(name: 'Manjlegaon', state: 'Maharashtra'),
  City(name: 'Wankaner', state: 'Gujarat'),
  City(name: 'Sillod', state: 'Maharashtra'),
  City(name: 'Nidadavole', state: 'Andhra Pradesh'),
  City(name: 'Surapura', state: 'Karnataka'),
  City(name: 'Rajagangapur', state: 'Odisha'),
  City(name: 'Sheikhpura', state: 'Bihar'),
  City(name: 'Parlakhemundi', state: 'Odisha'),
  City(name: 'Kalimpong', state: 'West Bengal'),
  City(name: 'Siruguppa', state: 'Karnataka'),
  City(name: 'Arvi', state: 'Maharashtra'),
  City(name: 'Limbdi', state: 'Gujarat'),
  City(name: 'Barpeta', state: 'Assam'),
  City(name: 'Manglaur', state: 'Uttarakhand'),
  City(name: 'Repalle', state: 'Andhra Pradesh'),
  City(name: 'Mudhol', state: 'Karnataka'),
  City(name: 'Shujalpur', state: 'Madhya Pradesh'),
  City(name: 'Mandvi', state: 'Gujarat'),
  City(name: 'Thangadh', state: 'Gujarat'),
  City(name: 'Sironj', state: 'Madhya Pradesh'),
  City(name: 'Nandura', state: 'Maharashtra'),
  City(name: 'Shoranur', state: 'Kerala'),
  City(name: 'Nathdwara', state: 'Rajasthan'),
  City(name: 'Periyakulam', state: 'Tamil Nadu'),
  City(name: 'Sultanganj', state: 'Bihar'),
  City(name: 'Medak', state: 'Telangana'),
  City(name: 'Narayanpet', state: 'Telangana'),
  City(name: 'Raxaul Bazar', state: 'Bihar'),
  City(name: 'Rajauri', state: 'Jammu and Kashmir'),
  City(name: 'Pernampattu', state: 'Tamil Nadu'),
  City(name: 'Nainital', state: 'Uttarakhand'),
  City(name: 'Ramachandrapuram', state: 'Andhra Pradesh'),
  City(name: 'Vaijapur', state: 'Maharashtra'),
  City(name: 'Nangal', state: 'Punjab'),
  City(name: 'Sidlaghatta', state: 'Karnataka'),
  City(name: 'Punch', state: 'Jammu and Kashmir'),
  City(name: 'Pandhurna', state: 'Madhya Pradesh'),
  City(name: 'Wadgaon Road', state: 'Maharashtra'),
  City(name: 'Talcher', state: 'Odisha'),
  City(name: 'Varkala', state: 'Kerala'),
  City(name: 'Pilani', state: 'Rajasthan'),
  City(name: 'Nowgong', state: 'Madhya Pradesh'),
  City(name: 'Naila Janjgir', state: 'Chhattisgarh'),
  City(name: 'Mapusa', state: 'Goa'),
  City(name: 'Vellakoil', state: 'Tamil Nadu'),
  City(name: 'Merta City', state: 'Rajasthan'),
  City(name: 'Sivaganga', state: 'Tamil Nadu'),
  City(name: 'Mandideep', state: 'Madhya Pradesh'),
  City(name: 'Sailu', state: 'Maharashtra'),
  City(name: 'Vyara', state: 'Gujarat'),
  City(name: 'Kovvur', state: 'Andhra Pradesh'),
  City(name: 'Vadalur', state: 'Tamil Nadu'),
  City(name: 'Nawabganj', state: 'Uttar Pradesh'),
  City(name: 'Padra', state: 'Gujarat'),
  City(name: 'Sainthia', state: 'West Bengal'),
  City(name: 'Siana', state: 'Uttar Pradesh'),
  City(name: 'Shahpur', state: 'Karnataka'),
  City(name: 'Sojat', state: 'Rajasthan'),
  City(name: 'Noorpur', state: 'Uttar Pradesh'),
  City(name: 'Paravoor', state: 'Kerala'),
  City(name: 'Murtijapur', state: 'Maharashtra'),
  City(name: 'Ramnagar', state: 'Bihar'),
  City(name: 'Sundargarh', state: 'Odisha'),
  City(name: 'Taki', state: 'West Bengal'),
  City(name: 'Saundatti-Yellamma', state: 'Karnataka'),
  City(name: 'Pathanamthitta', state: 'Kerala'),
  City(name: 'Wadi', state: 'Karnataka'),
  City(name: 'Rameshwaram', state: 'Tamil Nadu'),
  City(name: 'Tasgaon', state: 'Maharashtra'),
  City(name: 'Sikandra Rao', state: 'Uttar Pradesh'),
  City(name: 'Sihora', state: 'Madhya Pradesh'),
  City(name: 'Tiruvethipuram', state: 'Tamil Nadu'),
  City(name: 'Tiruvuru', state: 'Andhra Pradesh'),
  City(name: 'Mehkar', state: 'Maharashtra'),
  City(name: 'Peringathur', state: 'Kerala'),
  City(name: 'Perambalur', state: 'Tamil Nadu'),
  City(name: 'Manvi', state: 'Karnataka'),
  City(name: 'Zunheboto', state: 'Nagaland'),
  City(name: 'Mahnar Bazar', state: 'Bihar'),
  City(name: 'Attingal', state: 'Kerala'),
  City(name: 'Shahbad', state: 'Haryana'),
  City(name: 'Puranpur', state: 'Uttar Pradesh'),
  City(name: 'Nelamangala', state: 'Karnataka'),
  City(name: 'Nakodar', state: 'Punjab'),
  City(name: 'Lunawada', state: 'Gujarat'),
  City(name: 'Murshidabad', state: 'West Bengal'),
  City(name: 'Mahe', state: 'Puducherry'),
  City(name: 'Lanka', state: 'Assam'),
  City(name: 'Rudauli', state: 'Uttar Pradesh'),
  City(name: 'Tuensang', state: 'Nagaland'),
  City(name: 'Lakshmeshwar', state: 'Karnataka'),
  City(name: 'Zira', state: 'Punjab'),
  City(name: 'Yawal', state: 'Maharashtra'),
  City(name: 'Thana Bhawan', state: 'Uttar Pradesh'),
  City(name: 'Ramdurg', state: 'Karnataka'),
  City(name: 'Pulgaon', state: 'Maharashtra'),
  City(name: 'Sadasivpet', state: 'Telangana'),
  City(name: 'Nargund', state: 'Karnataka'),
  City(name: 'Neem-Ka-Thana', state: 'Rajasthan'),
  City(name: 'Memari', state: 'West Bengal'),
  City(name: 'Nilanga', state: 'Maharashtra'),
  City(name: 'Naharlagun', state: 'Arunachal Pradesh'),
  City(name: 'Pakaur', state: 'Jharkhand'),
  City(name: 'Wai', state: 'Maharashtra'),
  City(name: 'Tarikere', state: 'Karnataka'),
  City(name: 'Malavalli', state: 'Karnataka'),
  City(name: 'Raisen', state: 'Madhya Pradesh'),
  City(name: 'Lahar', state: 'Madhya Pradesh'),
  City(name: 'Uravakonda', state: 'Andhra Pradesh'),
  City(name: 'Savanur', state: 'Karnataka'),
  City(name: 'Sirohi', state: 'Rajasthan'),
  City(name: 'Udhampur', state: 'Jammu and Kashmir'),
  City(name: 'Umarga', state: 'Maharashtra'),
  City(name: 'Pratapgarh', state: 'Rajasthan'),
  City(name: 'Lingsugur', state: 'Karnataka'),
  City(name: 'Usilampatti', state: 'Tamil Nadu'),
  City(name: 'Palia Kalan', state: 'Uttar Pradesh'),
  City(name: 'Wokha', state: 'Nagaland'),
  City(name: 'Rajpipla', state: 'Gujarat'),
  City(name: 'Vijayapura', state: 'Karnataka'),
  City(name: 'Rawatbhata', state: 'Rajasthan'),
  City(name: 'Sangaria', state: 'Rajasthan'),
  City(name: 'Paithan', state: 'Maharashtra'),
  City(name: 'Rahuri', state: 'Maharashtra'),
  City(name: 'Patti', state: 'Punjab'),
  City(name: 'Zaidpur', state: 'Uttar Pradesh'),
  City(name: 'Lalsot', state: 'Rajasthan'),
  City(name: 'Maihar', state: 'Madhya Pradesh'),
  City(name: 'Vedaranyam', state: 'Tamil Nadu'),
  City(name: 'Nawapur', state: 'Maharashtra'),
  City(name: 'Solan', state: 'Himachal Pradesh'),
  City(name: 'Vapi', state: 'Gujarat'),
  City(name: 'Sanawad', state: 'Madhya Pradesh'),
  City(name: 'Warisaliganj', state: 'Bihar'),
  City(name: 'Revelganj', state: 'Bihar'),
  City(name: 'Sabalgarh', state: 'Madhya Pradesh'),
  City(name: 'Tuljapur', state: 'Maharashtra'),
  City(name: 'Simdega', state: 'Jharkhand'),
  City(name: 'Musabani', state: 'Jharkhand'),
  City(name: 'Kodungallur', state: 'Kerala'),
  City(name: 'Phulabani', state: 'Odisha'),
  City(name: 'Umreth', state: 'Gujarat'),
  City(name: 'Narsipatnam', state: 'Andhra Pradesh'),
  City(name: 'Nautanwa', state: 'Uttar Pradesh'),
  City(name: 'Rajgir', state: 'Bihar'),
  City(name: 'Yellandu', state: 'Telangana'),
  City(name: 'Sathyamangalam', state: 'Tamil Nadu'),
  City(name: 'Pilibanga', state: 'Rajasthan'),
  City(name: 'Morshi', state: 'Maharashtra'),
  City(name: 'Pehowa', state: 'Haryana'),
  City(name: 'Sonepur', state: 'Bihar'),
  City(name: 'Pappinisseri', state: 'Kerala'),
  City(name: 'Zamania', state: 'Uttar Pradesh'),
  City(name: 'Mihijam', state: 'Jharkhand'),
  City(name: 'Purna', state: 'Maharashtra'),
  City(name: 'Puliyankudi', state: 'Tamil Nadu'),
  City(name: 'Shikarpur, Bulandshahr', state: 'Uttar Pradesh'),
  City(name: 'Umaria', state: 'Madhya Pradesh'),
  City(name: 'Porsa', state: 'Madhya Pradesh'),
  City(name: 'Naugawan Sadat', state: 'Uttar Pradesh'),
  City(name: 'Fatehpur Sikri', state: 'Uttar Pradesh'),
  City(name: 'Manuguru', state: 'Telangana'),
  City(name: 'Udaipur', state: 'Tripura'),
  City(name: 'Pipar City', state: 'Rajasthan'),
  City(name: 'Pattamundai', state: 'Odisha'),
  City(name: 'Nanjikottai', state: 'Tamil Nadu'),
  City(name: 'Taranagar', state: 'Rajasthan'),
  City(name: 'Yerraguntla', state: 'Andhra Pradesh'),
  City(name: 'Satana', state: 'Maharashtra'),
  City(name: 'Sherghati', state: 'Bihar'),
  City(name: 'Sankeshwara', state: 'Karnataka'),
  City(name: 'Madikeri', state: 'Karnataka'),
  City(name: 'Thuraiyur', state: 'Tamil Nadu'),
  City(name: 'Sanand', state: 'Gujarat'),
  City(name: 'Rajula', state: 'Gujarat'),
  City(name: 'Kyathampalle', state: 'Telangana'),
  City(name: 'Shahabad, Rampur', state: 'Uttar Pradesh'),
  City(name: 'Tilda Newra', state: 'Chhattisgarh'),
  City(name: 'Narsinghgarh', state: 'Madhya Pradesh'),
  City(name: 'Chittur-Thathamangalam', state: 'Kerala'),
  City(name: 'Malaj Khand', state: 'Madhya Pradesh'),
  City(name: 'Sarangpur', state: 'Madhya Pradesh'),
  City(name: 'Robertsganj', state: 'Uttar Pradesh'),
  City(name: 'Sirkali', state: 'Tamil Nadu'),
  City(name: 'Radhanpur', state: 'Gujarat'),
  City(name: 'Tiruchendur', state: 'Tamil Nadu'),
  City(name: 'Utraula', state: 'Uttar Pradesh'),
  City(name: 'Patratu', state: 'Jharkhand'),
  City(name: 'Vijainagar, Ajmer', state: 'Rajasthan'),
  City(name: 'Periyasemur', state: 'Tamil Nadu'),
  City(name: 'Pathri', state: 'Maharashtra'),
  City(name: 'Sadabad', state: 'Uttar Pradesh'),
  City(name: 'Talikota', state: 'Karnataka'),
  City(name: 'Sinnar', state: 'Maharashtra'),
  City(name: 'Mungeli', state: 'Chhattisgarh'),
  City(name: 'Sedam', state: 'Karnataka'),
  City(name: 'Shikaripur', state: 'Karnataka'),
  City(name: 'Sumerpur', state: 'Rajasthan'),
  City(name: 'Sattur', state: 'Tamil Nadu'),
  City(name: 'Sugauli', state: 'Bihar'),
  City(name: 'Lumding', state: 'Assam'),
  City(name: 'Vandavasi', state: 'Tamil Nadu'),
  City(name: 'Titlagarh', state: 'Odisha'),
  City(name: 'Uchgaon', state: 'Maharashtra'),
  City(name: 'Mokokchung', state: 'Nagaland'),
  City(name: 'Paschim Punropara', state: 'West Bengal'),
  City(name: 'Sagwara', state: 'Rajasthan'),
  City(name: 'Ramganj Mandi', state: 'Rajasthan'),
  City(name: 'Tarakeswar', state: 'West Bengal'),
  City(name: 'Mahalingapura', state: 'Karnataka'),
  City(name: 'Dharmanagar', state: 'Tripura'),
  City(name: 'Mahemdabad', state: 'Gujarat'),
  City(name: 'Manendragarh', state: 'Chhattisgarh'),
  City(name: 'Uran', state: 'Maharashtra'),
  City(name: 'Tharamangalam', state: 'Tamil Nadu'),
  City(name: 'Tirukkoyilur', state: 'Tamil Nadu'),
  City(name: 'Pen', state: 'Maharashtra'),
  City(name: 'Makhdumpur', state: 'Bihar'),
  City(name: 'Maner', state: 'Bihar'),
  City(name: 'Oddanchatram', state: 'Tamil Nadu'),
  City(name: 'Palladam', state: 'Tamil Nadu'),
  City(name: 'Mundi', state: 'Madhya Pradesh'),
  City(name: 'Nabarangapur', state: 'Odisha'),
  City(name: 'Mudalagi', state: 'Karnataka'),
  City(name: 'Samalkha', state: 'Haryana'),
  City(name: 'Nepanagar', state: 'Madhya Pradesh'),
  City(name: 'Karjat', state: 'Maharashtra'),
  City(name: 'Ranavav', state: 'Gujarat'),
  City(name: 'Pedana', state: 'Andhra Pradesh'),
  City(name: 'Pinjore', state: 'Haryana'),
  City(name: 'Lakheri', state: 'Rajasthan'),
  City(name: 'Pasan', state: 'Madhya Pradesh'),
  City(name: 'Puttur', state: 'Andhra Pradesh'),
  City(name: 'Vadakkuvalliyur', state: 'Tamil Nadu'),
  City(name: 'Tirukalukundram', state: 'Tamil Nadu'),
  City(name: 'Mahidpur', state: 'Madhya Pradesh'),
  City(name: 'Mussoorie', state: 'Uttarakhand'),
  City(name: 'Muvattupuzha', state: 'Kerala'),
  City(name: 'Rasra', state: 'Uttar Pradesh'),
  City(name: 'Udaipurwati', state: 'Rajasthan'),
  City(name: 'Manwath', state: 'Maharashtra'),
  City(name: 'Adoor', state: 'Kerala'),
  City(name: 'Uthamapalayam', state: 'Tamil Nadu'),
  City(name: 'Partur', state: 'Maharashtra'),
  City(name: 'Nahan', state: 'Himachal Pradesh'),
  City(name: 'Ladwa', state: 'Haryana'),
  City(name: 'Mankachar', state: 'Assam'),
  City(name: 'Nongstoin', state: 'Meghalaya'),
  City(name: 'Losal', state: 'Rajasthan'),
  City(name: 'Sri Madhopur', state: 'Rajasthan'),
  City(name: 'Ramngarh', state: 'Rajasthan'),
  City(name: 'Mavelikkara', state: 'Kerala'),
  City(name: 'Rawatsar', state: 'Rajasthan'),
  City(name: 'Rajakhera', state: 'Rajasthan'),
  City(name: 'Lar', state: 'Uttar Pradesh'),
  City(name: 'Lal Gopalganj Nindaura', state: 'Uttar Pradesh'),
  City(name: 'Muddebihal', state: 'Karnataka'),
  City(name: 'Sirsaganj', state: 'Uttar Pradesh'),
  City(name: 'Shahpura', state: 'Rajasthan'),
  City(name: 'Surandai', state: 'Tamil Nadu'),
  City(name: 'Sangole', state: 'Maharashtra'),
  City(name: 'Pavagada', state: 'Karnataka'),
  City(name: 'Tharad', state: 'Gujarat'),
  City(name: 'Mansa', state: 'Gujarat'),
  City(name: 'Umbergaon', state: 'Gujarat'),
  City(name: 'Mavoor', state: 'Kerala'),
  City(name: 'Nalbari', state: 'Assam'),
  City(name: 'Talaja', state: 'Gujarat'),
  City(name: 'Malur', state: 'Karnataka'),
  City(name: 'Mangrulpir', state: 'Maharashtra'),
  City(name: 'Soro', state: 'Odisha'),
  City(name: 'Shahpura', state: 'Rajasthan'),
  City(name: 'Vadnagar', state: 'Gujarat'),
  City(name: 'Raisinghnagar', state: 'Rajasthan'),
  City(name: 'Sindhagi', state: 'Karnataka'),
  City(name: 'Sanduru', state: 'Karnataka'),
  City(name: 'Sohna', state: 'Haryana'),
  City(name: 'Manavadar', state: 'Gujarat'),
  City(name: 'Pihani', state: 'Uttar Pradesh'),
  City(name: 'Safidon', state: 'Haryana'),
  City(name: 'Risod', state: 'Maharashtra'),
  City(name: 'Rosera', state: 'Bihar'),
  City(name: 'Sankari', state: 'Tamil Nadu'),
  City(name: 'Malpura', state: 'Rajasthan'),
  City(name: 'Sonamukhi', state: 'West Bengal'),
  City(name: 'Shamsabad, Agra', state: 'Uttar Pradesh'),
  City(name: 'Nokha', state: 'Bihar'),
  City(name: 'PandUrban Agglomeration', state: 'West Bengal'),
  City(name: 'Mainaguri', state: 'West Bengal'),
  City(name: 'Afzalpur', state: 'Karnataka'),
  City(name: 'Shirur', state: 'Maharashtra'),
  City(name: 'Salaya', state: 'Gujarat'),
  City(name: 'Shenkottai', state: 'Tamil Nadu'),
  City(name: 'Pratapgarh', state: 'Tripura'),
  City(name: 'Vadipatti', state: 'Tamil Nadu'),
  City(name: 'Nagarkurnool', state: 'Telangana'),
  City(name: 'Savner', state: 'Maharashtra'),
  City(name: 'Sasvad', state: 'Maharashtra'),
  City(name: 'Rudrapur', state: 'Uttar Pradesh'),
  City(name: 'Soron', state: 'Uttar Pradesh'),
  City(name: 'Sholingur', state: 'Tamil Nadu'),
  City(name: 'Pandharkaoda', state: 'Maharashtra'),
  City(name: 'Perumbavoor', state: 'Kerala'),
  City(name: 'Maddur', state: 'Karnataka'),
  City(name: 'Nadbai', state: 'Rajasthan'),
  City(name: 'Talode', state: 'Maharashtra'),
  City(name: 'Shrigonda', state: 'Maharashtra'),
  City(name: 'Madhugiri', state: 'Karnataka'),
  City(name: 'Tekkalakote', state: 'Karnataka'),
  City(name: 'Seoni-Malwa', state: 'Madhya Pradesh'),
  City(name: 'Shirdi', state: 'Maharashtra'),
  City(name: 'SUrban Agglomerationr', state: 'Uttar Pradesh'),
  City(name: 'Terdal', state: 'Karnataka'),
  City(name: 'Raver', state: 'Maharashtra'),
  City(name: 'Tirupathur', state: 'Tamil Nadu'),
  City(name: 'Taraori', state: 'Haryana'),
  City(name: 'Mukhed', state: 'Maharashtra'),
  City(name: 'Manachanallur', state: 'Tamil Nadu'),
  City(name: 'Rehli', state: 'Madhya Pradesh'),
  City(name: 'Sanchore', state: 'Rajasthan'),
  City(name: 'Rajura', state: 'Maharashtra'),
  City(name: 'Piro', state: 'Bihar'),
  City(name: 'Mudabidri', state: 'Karnataka'),
  City(name: 'Vadgaon Kasba', state: 'Maharashtra'),
  City(name: 'Nagar', state: 'Rajasthan'),
  City(name: 'Vijapur', state: 'Gujarat'),
  City(name: 'Viswanatham', state: 'Tamil Nadu'),
  City(name: 'Polur', state: 'Tamil Nadu'),
  City(name: 'Panagudi', state: 'Tamil Nadu'),
  City(name: 'Manawar', state: 'Madhya Pradesh'),
  City(name: 'Tehri', state: 'Uttarakhand'),
  City(name: 'Samdhan', state: 'Uttar Pradesh'),
  City(name: 'Pardi', state: 'Gujarat'),
  City(name: 'Rahatgarh', state: 'Madhya Pradesh'),
  City(name: 'Panagar', state: 'Madhya Pradesh'),
  City(name: 'Uthiramerur', state: 'Tamil Nadu'),
  City(name: 'Tirora', state: 'Maharashtra'),
  City(name: 'Rangia', state: 'Assam'),
  City(name: 'Sahjanwa', state: 'Uttar Pradesh'),
  City(name: 'Wara Seoni', state: 'Madhya Pradesh'),
  City(name: 'Magadi', state: 'Karnataka'),
  City(name: 'Rajgarh (Alwar)', state: 'Rajasthan'),
  City(name: 'Rafiganj', state: 'Bihar'),
  City(name: 'Tarana', state: 'Madhya Pradesh'),
  City(name: 'Rampur Maniharan', state: 'Uttar Pradesh'),
  City(name: 'Sheoganj', state: 'Rajasthan'),
  City(name: 'Raikot', state: 'Punjab'),
  City(name: 'Pauri', state: 'Uttarakhand'),
  City(name: 'Sumerpur', state: 'Uttar Pradesh'),
  City(name: 'Navalgund', state: 'Karnataka'),
  City(name: 'Shahganj', state: 'Uttar Pradesh'),
  City(name: 'Marhaura', state: 'Bihar'),
  City(name: 'Tulsipur', state: 'Uttar Pradesh'),
  City(name: 'Sadri', state: 'Rajasthan'),
  City(name: 'Thiruthuraipoondi', state: 'Tamil Nadu'),
  City(name: 'Shiggaon', state: 'Karnataka'),
  City(name: 'Pallapatti', state: 'Tamil Nadu'),
  City(name: 'Mahendragarh', state: 'Haryana'),
  City(name: 'Sausar', state: 'Madhya Pradesh'),
  City(name: 'Ponneri', state: 'Tamil Nadu'),
  City(name: 'Mahad', state: 'Maharashtra'),
  City(name: 'Lohardaga', state: 'Jharkhand'),
  City(name: 'Tirwaganj', state: 'Uttar Pradesh'),
  City(name: 'Margherita', state: 'Assam'),
  City(name: 'Sundarnagar', state: 'Himachal Pradesh'),
  City(name: 'Rajgarh', state: 'Madhya Pradesh'),
  City(name: 'Mangaldoi', state: 'Assam'),
  City(name: 'Renigunta', state: 'Andhra Pradesh'),
  City(name: 'Longowal', state: 'Punjab'),
  City(name: 'Ratia', state: 'Haryana'),
  City(name: 'Lalgudi', state: 'Tamil Nadu'),
  City(name: 'Shrirangapattana', state: 'Karnataka'),
  City(name: 'Niwari', state: 'Madhya Pradesh'),
  City(name: 'Natham', state: 'Tamil Nadu'),
  City(name: 'Unnamalaikadai', state: 'Tamil Nadu'),
  City(name: 'PurqUrban Agglomerationzi', state: 'Uttar Pradesh'),
  City(name: 'Shamsabad, Farrukhabad', state: 'Uttar Pradesh'),
  City(name: 'Mirganj', state: 'Bihar'),
  City(name: 'Todaraisingh', state: 'Rajasthan'),
  City(name: 'Warhapur', state: 'Uttar Pradesh'),
  City(name: 'Rajam', state: 'Andhra Pradesh'),
  City(name: 'Urmar Tanda', state: 'Punjab'),
  City(name: 'Lonar', state: 'Maharashtra'),
  City(name: 'Powayan', state: 'Uttar Pradesh'),
  City(name: 'P.N.Patti', state: 'Tamil Nadu'),
  City(name: 'Palampur', state: 'Himachal Pradesh'),
  City(name: 'Srisailam Project (Right Flank Colony) Township', state: 'Andhra Pradesh'),
  City(name: 'Sindagi', state: 'Karnataka'),
  City(name: 'Sandi', state: 'Uttar Pradesh'),
  City(name: 'Vaikom', state: 'Kerala'),
  City(name: 'Malda', state: 'West Bengal'),
  City(name: 'Tharangambadi', state: 'Tamil Nadu'),
  City(name: 'Sakaleshapura', state: 'Karnataka'),
  City(name: 'Lalganj', state: 'Bihar'),
  City(name: 'Malkangiri', state: 'Odisha'),
  City(name: 'Rapar', state: 'Gujarat'),
  City(name: 'Mauganj', state: 'Madhya Pradesh'),
  City(name: 'Todabhim', state: 'Rajasthan'),
  City(name: 'Srinivaspur', state: 'Karnataka'),
  City(name: 'Murliganj', state: 'Bihar'),
  City(name: 'Reengus', state: 'Rajasthan'),
  City(name: 'Sawantwadi', state: 'Maharashtra'),
  City(name: 'Tittakudi', state: 'Tamil Nadu'),
  City(name: 'Lilong', state: 'Manipur'),
  City(name: 'Rajaldesar', state: 'Rajasthan'),
  City(name: 'Pathardi', state: 'Maharashtra'),
  City(name: 'Achhnera', state: 'Uttar Pradesh'),
  City(name: 'Pacode', state: 'Tamil Nadu'),
  City(name: 'Naraura', state: 'Uttar Pradesh'),
  City(name: 'Nakur', state: 'Uttar Pradesh'),
  City(name: 'Palai', state: 'Kerala'),
  City(name: 'Morinda, India', state: 'Punjab'),
  City(name: 'Manasa', state: 'Madhya Pradesh'),
  City(name: 'Nainpur', state: 'Madhya Pradesh'),
  City(name: 'Sahaspur', state: 'Uttar Pradesh'),
  City(name: 'Pauni', state: 'Maharashtra'),
  City(name: 'Prithvipur', state: 'Madhya Pradesh'),
  City(name: 'Ramtek', state: 'Maharashtra'),
  City(name: 'Silapathar', state: 'Assam'),
  City(name: 'Songadh', state: 'Gujarat'),
  City(name: 'Safipur', state: 'Uttar Pradesh'),
  City(name: 'Sohagpur', state: 'Madhya Pradesh'),
  City(name: 'Mul', state: 'Maharashtra'),
  City(name: 'Sadulshahar', state: 'Rajasthan'),
  City(name: 'Phillaur', state: 'Punjab'),
  City(name: 'Sambhar', state: 'Rajasthan'),
  City(name: 'Prantij', state: 'Rajasthan'),
  City(name: 'Nagla', state: 'Uttarakhand'),
  City(name: 'Pattran', state: 'Punjab'),
  City(name: 'Mount Abu', state: 'Rajasthan'),
  City(name: 'Reoti', state: 'Uttar Pradesh'),
  City(name: 'Tenu dam-cum-Kathhara', state: 'Jharkhand'),
  City(name: 'Panchla', state: 'West Bengal'),
  City(name: 'Sitarganj', state: 'Uttarakhand'),
  City(name: 'Pasighat', state: 'Arunachal Pradesh'),
  City(name: 'Motipur', state: 'Bihar'),
  City(name: 'O\' Valley', state: 'Tamil Nadu'),
  City(name: 'Raghunathpur', state: 'West Bengal'),
  City(name: 'Suriyampalayam', state: 'Tamil Nadu'),
  City(name: 'Qadian', state: 'Punjab'),
  City(name: 'Rairangpur', state: 'Odisha'),
  City(name: 'Silvassa', state: 'Dadra and Nagar Haveli'),
  City(name: 'Nowrozabad (Khodargama)', state: 'Madhya Pradesh'),
  City(name: 'Mangrol', state: 'Rajasthan'),
  City(name: 'Soyagaon', state: 'Maharashtra'),
  City(name: 'Sujanpur', state: 'Punjab'),
  City(name: 'Manihari', state: 'Bihar'),
  City(name: 'Sikanderpur', state: 'Uttar Pradesh'),
  City(name: 'Mangalvedhe', state: 'Maharashtra'),
  City(name: 'Phulera', state: 'Rajasthan'),
  City(name: 'Ron', state: 'Karnataka'),
  City(name: 'Sholavandan', state: 'Tamil Nadu'),
  City(name: 'Saidpur', state: 'Uttar Pradesh'),
  City(name: 'Shamgarh', state: 'Madhya Pradesh'),
  City(name: 'Thammampatti', state: 'Tamil Nadu'),
  City(name: 'Maharajpur', state: 'Madhya Pradesh'),
  City(name: 'Multai', state: 'Madhya Pradesh'),
  City(name: 'Mukerian', state: 'Punjab'),
  City(name: 'Sirsi', state: 'Uttar Pradesh'),
  City(name: 'Purwa', state: 'Uttar Pradesh'),
  City(name: 'Sheohar', state: 'Bihar'),
  City(name: 'Namagiripettai', state: 'Tamil Nadu'),
  City(name: 'Parasi', state: 'Uttar Pradesh'),
  City(name: 'Lathi', state: 'Gujarat'),
  City(name: 'Lalganj', state: 'Uttar Pradesh'),
  City(name: 'Narkhed', state: 'Maharashtra'),
  City(name: 'Mathabhanga', state: 'West Bengal'),
  City(name: 'Shendurjana', state: 'Maharashtra'),
  City(name: 'Peravurani', state: 'Tamil Nadu'),
  City(name: 'Mariani', state: 'Assam'),
  City(name: 'Phulpur', state: 'Uttar Pradesh'),
  City(name: 'Rania', state: 'Haryana'),
  City(name: 'Pali', state: 'Madhya Pradesh'),
  City(name: 'Pachore', state: 'Madhya Pradesh'),
  City(name: 'Parangipettai', state: 'Tamil Nadu'),
  City(name: 'Pudupattinam', state: 'Tamil Nadu'),
  City(name: 'Panniyannur', state: 'Kerala'),
  City(name: 'Maharajganj', state: 'Bihar'),
  City(name: 'Rau', state: 'Madhya Pradesh'),
  City(name: 'Monoharpur', state: 'West Bengal'),
  City(name: 'Mandawa', state: 'Rajasthan'),
  City(name: 'Marigaon', state: 'Assam'),
  City(name: 'Pallikonda', state: 'Tamil Nadu'),
  City(name: 'Pindwara', state: 'Rajasthan'),
  City(name: 'Shishgarh', state: 'Uttar Pradesh'),
  City(name: 'Patur', state: 'Maharashtra'),
  City(name: 'Mayang Imphal', state: 'Manipur'),
  City(name: 'Mhowgaon', state: 'Madhya Pradesh'),
  City(name: 'Guruvayoor', state: 'Kerala'),
  City(name: 'Mhaswad', state: 'Maharashtra'),
  City(name: 'Sahawar', state: 'Uttar Pradesh'),
  City(name: 'Sivagiri', state: 'Tamil Nadu'),
  City(name: 'Mundargi', state: 'Karnataka'),
  City(name: 'Punjaipugalur', state: 'Tamil Nadu'),
  City(name: 'Kailasahar', state: 'Tripura'),
  City(name: 'Samthar', state: 'Uttar Pradesh'),
  City(name: 'Sakti', state: 'Chhattisgarh'),
  City(name: 'Sadalagi', state: 'Karnataka'),
  City(name: 'Silao', state: 'Bihar'),
  City(name: 'Mandalgarh', state: 'Rajasthan'),
  City(name: 'Loha', state: 'Maharashtra'),
  City(name: 'Pukhrayan', state: 'Uttar Pradesh'),
  City(name: 'Padmanabhapuram', state: 'Tamil Nadu'),
  City(name: 'Belonia', state: 'Tripura'),
  City(name: 'Saiha', state: 'Mizoram'),
  City(name: 'Srirampore', state: 'West Bengal'),
  City(name: 'Talwara', state: 'Punjab'),
  City(name: 'Puthuppally', state: 'Kerala'),
  City(name: 'Khowai', state: 'Tripura'),
  City(name: 'Vijaypur', state: 'Madhya Pradesh'),
  City(name: 'Takhatgarh', state: 'Rajasthan'),
  City(name: 'Thirupuvanam', state: 'Tamil Nadu'),
  City(name: 'Adra', state: 'West Bengal'),
  City(name: 'Piriyapatna', state: 'Karnataka'),
  City(name: 'Obra', state: 'Uttar Pradesh'),
  City(name: 'Adalaj', state: 'Gujarat'),
  City(name: 'Nandgaon', state: 'Maharashtra'),
  City(name: 'Barh', state: 'Bihar'),
  City(name: 'Chhapra', state: 'Gujarat'),
  City(name: 'Panamattom', state: 'Kerala'),
  City(name: 'Niwai', state: 'Uttar Pradesh'),
  City(name: 'Bageshwar', state: 'Uttarakhand'),
  City(name: 'Tarbha', state: 'Odisha'),
  City(name: 'Adyar', state: 'Karnataka'),
  City(name: 'Narsinghgarh', state: 'Madhya Pradesh'),
  City(name: 'Warud', state: 'Maharashtra'),
  City(name: 'Asarganj', state: 'Bihar'),
  City(name: 'Sarsod', state: 'Haryana'),
  City(name: 'Gandhinagar', state: 'Gujarat'),
  City(name: 'Kullu', state: 'Himachal Pradesh'),
  City(name: 'Manali', state: 'Himachal Praddesh'),
  City(name: 'Mirzapur', state: 'Uttar Pradesh'),
  City(name: 'Kota', state: 'Rajasthan'),
  City(name: 'Dispur', state: 'Assam'),
];
